package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/wricardo/ai-http-bin/graph/model"
)

// DeleteRequest is the resolver for the deleteRequest field.
func (r *mutationResolver) DeleteRequest(ctx context.Context, id string) (bool, error) {
	return r.Store.DeleteRequest(id), nil
}

// ClearRequests is the resolver for the clearRequests field.
func (r *mutationResolver) ClearRequests(ctx context.Context, tokenID string) (bool, error) {
	return r.Store.ClearRequests(tokenID), nil
}

// Request is the resolver for the request field.
func (r *queryResolver) Request(ctx context.Context, id string) (*model.Request, error) {
	req, ok := r.Store.GetRequest(id)
	if !ok {
		return nil, nil
	}
	return storeRequestToModel(req), nil
}

// Requests is the resolver for the requests field.
func (r *queryResolver) Requests(ctx context.Context, tokenID string, page *int, perPage *int, sorting *string) (*model.RequestPage, error) {
	p, pp := 1, 50
	if page != nil {
		p = *page
	}
	if perPage != nil {
		pp = *perPage
	}
	newest := sorting != nil && *sorting == "newest"

	reqs, total := r.Store.ListRequests(tokenID, p, pp, newest)

	data := make([]*model.Request, len(reqs))
	for i, req := range reqs {
		data[i] = storeRequestToModel(req)
	}

	from := (p-1)*pp + 1
	to := from + len(data) - 1
	if len(data) == 0 {
		from, to = 0, 0
	}

	return &model.RequestPage{
		Data:        data,
		Total:       total,
		PerPage:     pp,
		CurrentPage: p,
		IsLastPage:  to >= total,
		From:        from,
		To:          to,
	}, nil
}

// RequestReceived is the resolver for the requestReceived field.
func (r *subscriptionResolver) RequestReceived(ctx context.Context, tokenID string) (<-chan *model.RequestEvent, error) {
	sub := r.Store.Subscribe(tokenID)
	ch := make(chan *model.RequestEvent, 1)

	go func() {
		defer r.Store.Unsubscribe(sub)
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-sub.Ch:
				if !ok {
					return
				}
				out := &model.RequestEvent{
					Request:   storeRequestToModel(ev.Request),
					Total:     ev.Total,
					Truncated: ev.Truncated,
				}
				select {
				case ch <- out:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}
