package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/wricardo/ai-http-bin/graph/model"
	"github.com/wricardo/ai-http-bin/internal/store"
)

// CreateToken is the resolver for the createToken field.
func (r *mutationResolver) CreateToken(ctx context.Context, defaultStatus *int, defaultContent *string, defaultContentType *string, timeout *int, cors *bool) (*model.Token, error) {
	ip, ua := "", ""
	if gc := GinContextFrom(ctx); gc != nil {
		ip = gc.ClientIP()
		ua = gc.Request.UserAgent()
	}
	agentID := AgentIDFromContext(ctx)
	t := r.Store.CreateToken(ip, ua, agentID)
	patchToken(t, defaultStatus, defaultContent, defaultContentType, timeout, cors)
	return storeTokenToModel(r.Store, r.BaseURL, t), nil
}

// UpdateToken is the resolver for the updateToken field.
func (r *mutationResolver) UpdateToken(ctx context.Context, id string, defaultStatus *int, defaultContent *string, defaultContentType *string, timeout *int, cors *bool) (*model.Token, error) {
	t, ok := r.Store.GetToken(id)
	if !ok {
		return nil, nil
	}
	patchToken(t, defaultStatus, defaultContent, defaultContentType, timeout, cors)
	r.Store.UpdateToken(t.ID, t.DefaultContent, t.DefaultContentType, t.DefaultStatus, t.Timeout, t.Cors)
	return storeTokenToModel(r.Store, r.BaseURL, t), nil
}

// ToggleCors is the resolver for the toggleCors field.
func (r *mutationResolver) ToggleCors(ctx context.Context, id string) (bool, error) {
	enabled, ok := r.Store.ToggleCors(id)
	if !ok {
		return false, nil
	}
	return enabled, nil
}

// DeleteToken is the resolver for the deleteToken field.
func (r *mutationResolver) DeleteToken(ctx context.Context, id string) (bool, error) {
	return r.Store.DeleteToken(id), nil
}

// ClaimToken is the resolver for the claimToken field.
func (r *mutationResolver) ClaimToken(ctx context.Context, id string) (*model.Token, error) {
	agentID := AgentIDFromContext(ctx)
	if agentID == "" {
		return nil, fmt.Errorf("X-Agent-Id header required to claim a token")
	}
	t, ok := r.Store.ClaimToken(id, agentID)
	if !ok {
		return nil, fmt.Errorf("token not found or already claimed")
	}
	return storeTokenToModel(r.Store, r.BaseURL, t), nil
}

// Token is the resolver for the token field.
func (r *queryResolver) Token(ctx context.Context, id string) (*model.Token, error) {
	t, ok := r.Store.GetToken(id)
	if !ok {
		return nil, nil
	}
	return storeTokenToModel(r.Store, r.BaseURL, t), nil
}

// Tokens is the resolver for the tokens field.
func (r *queryResolver) Tokens(ctx context.Context) ([]*model.Token, error) {
	agentID := AgentIDFromContext(ctx)
	var tokens []*store.Token
	if agentID != "" {
		tokens = r.Store.ListTokensByAgent(agentID)
	} else {
		tokens = r.Store.ListTokens()
	}
	result := make([]*model.Token, len(tokens))
	for i, t := range tokens {
		result[i] = storeTokenToModel(r.Store, r.BaseURL, t)
	}
	return result, nil
}

// Requests is the resolver for the requests field on Token.
func (r *tokenResolver) Requests(ctx context.Context, obj *model.Token) ([]*model.Request, error) {
	reqs, _ := r.Store.ListRequests(obj.ID, 1, 50, false)
	result := make([]*model.Request, len(reqs))
	for i, req := range reqs {
		result[i] = storeRequestToModel(req)
	}
	return result, nil
}

// Token returns TokenResolver implementation.
func (r *Resolver) Token() TokenResolver { return &tokenResolver{r} }

type tokenResolver struct{ *Resolver }
