// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GlobalVar struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}

type Request struct {
	ID        string `json:"id"`
	TokenID   string `json:"tokenId"`
	Method    string `json:"method"`
	URL       string `json:"url"`
	Hostname  string `json:"hostname"`
	Path      string `json:"path"`
	Headers   string `json:"headers"`
	Query     string `json:"query"`
	Body      string `json:"body"`
	FormData  string `json:"formData"`
	IP        string `json:"ip"`
	UserAgent string `json:"userAgent"`
	CreatedAt string `json:"createdAt"`
}

type RequestEvent struct {
	Request   *Request `json:"request"`
	Total     int      `json:"total"`
	Truncated bool     `json:"truncated"`
}

type RequestPage struct {
	Data        []*Request `json:"data"`
	Total       int        `json:"total"`
	PerPage     int        `json:"perPage"`
	CurrentPage int        `json:"currentPage"`
	IsLastPage  bool       `json:"isLastPage"`
	From        int        `json:"from"`
	To          int        `json:"to"`
}

type Subscription struct {
}

type Token struct {
	ID                 string     `json:"id"`
	AgentID            *string    `json:"agentId,omitempty"`
	URL                string     `json:"url"`
	IP                 string     `json:"ip"`
	UserAgent          string     `json:"userAgent"`
	CreatedAt          string     `json:"createdAt"`
	RequestCount       int        `json:"requestCount"`
	DefaultStatus      int        `json:"defaultStatus"`
	DefaultContent     string     `json:"defaultContent"`
	DefaultContentType string     `json:"defaultContentType"`
	Timeout            int        `json:"timeout"`
	Cors               bool       `json:"cors"`
	Script             string     `json:"script"`
	Requests           []*Request `json:"requests"`
}
